

services:
  postgres:
    image: postgres:14
    container_name: gutendex_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/app/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:

